title: Point85 OEE
email: point85.llc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Overall Equipment Effectiveness
author: Kent Randall
baseurl: "/oee" # the subpath of the site
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  point85

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: 'G-3HB3SKPRWT' 
  
include:
  - images
  - docs
  - files

header_pages:
  - index.md
  - implementation.md
  - applications.md
  - blog.md  
  - about.md
